<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>BLOG</title>


	<link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins&family=Roboto+Condensed&display=swap" rel="stylesheet">

    <link rel="STYLESHEET" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style type="text/css">
    	
    	
 
		li{
		  list-style:  none;

		}
		h1,h2{
		  margin: 0;
		  text-align: center;
		  color: black;
		}
		p{
			text-align: center;
			color: white;
			font-size: 30px;
		}
		ul{
		  margin: 0;
		  padding: 0;
		  list-style: none;
		}

		a{
		  text-decoration: none;
		  color: #FFFFFF;
		  font-size: 1rem;
		}
		a:hover{
		  color: orange;
		}
		.nav-link::after{
		  position: absolute;
		}
		*{
		  margin: 0;
		  padding: 0;
		  box-sizing: border-box;
		  list-style: none;
		  background-color: black;
		  font-size: 'Poppins',sans-serif;
		}
		header{
		  position: relative;
		  padding: 0 2rem;
		  z-index: 100;
		 
		  
		}
		.navbar{
		  width: 100%;
		  height: 60px;
		  max-width: 1200px;
		  margin: 0 auto;
		  display: flex;
		  align-items: center;
		  justify-content: space-between;
		  
		  
		}
		.navbar .nav-logo a{
		  font-size: 1.5rem;
		  font-weight: bold;
		  
		}
				.nav-list{
		  display: flex;
		  gap: 2rem;
		  
		}
		.nav-item{
		  margin-bottom: 1.5rem;
		}
		.nav-link{
		  color: white;
		  font-weight: bold;
		  font-size: 20px;
		}
		.navbar .toggle_btn{
		  color:#FFFFFF;
		  font-size: 1.5rem;
		  cursor: pointer;
		  display: none;
		}
		.action_btn{
		  background-color: orange;
		  color: #FFFFFF;
		  font-size: 0.8rem;
		  padding: 0.5rem 1rem;
		  border: none;
		  outline: none;
		  border-radius: 20px;
		  font-weight: bold;
		  cursor: pointer;
		  transition: scale 0.2 ease;
		}
		.action_btn:hover{
		  scale: 1.05;
		  color: white;
		}
		.action_btn:active{
		  scale: 0.95;
		}

		
		
		.blogpost{
			background-color: white;
			color: black;
			width: 1200px;
			margin-right: 10px;
			height: 70vh;
			margin-left: 20px;
			margin-top: 50px;
			margin-bottom: 50px;
			display: flex;
			border-radius: 20px;
			
		}
		.blogpost2{
			background-color: white;
			color: black;
			width: 1200px;
			margin-right: 10px;
			height: 70vh;
			margin-left: 20px;
			margin-top: 20px;
			margin-bottom: 50px;
			display: flex;
			border-radius: 20px;
			
		}
		
		.BLOGCONT{
			border-radius: 10px;
			margin-top: 20px;
			margin-left: 80px;
			width: 210px;
			height: 60vh;
			background-color: white;
		}
		.BLOGCONT2{
			border-radius: 10px;
			margin-top: 20px;
			margin-left: 90px;
			width: 600px;
			height: 60vh;
			background-color: white;
		}
		.BLOGCONT3{
			border-radius: 10px;
			margin-top: 20px;
			margin-left: 90px;
			width: 600px;
			height: 60vh;
			background-color: white;
		}
		.BLOGCONT4{
			background-color: white;
			border-radius: 10px;
			margin-top: 20px;
			margin-left: 90px;
			width: 600px;
			height: 60vh;
		}
		img{
			margin-left: 12px;
			border-radius: 10px;
			border: 4px solid black;
			margin-top: 20px;
		}
	

   </style>
</head>
<body>
<header>
	<div class="navbar">
        <div class="nav-logo"><a href="#"> DEFORESTATION</a></div>
        <div class="nav-menu" id="nav-menu"></div>
        <ul class="nav-list">
            <li class="nav-item"><a href="INDEX.PHP" class="nav-link">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link">about</a></li>
            <li class="nav-item"><a href="#" class="nav-link">contact</a></li>
            
        </ul>
        
        </div>
    
    </div>
</header>
	<article class="blogpost">
		
		<div class="BLOGCONT">
			<img src="images/images.jpeg" alt="">
		</div>
		<div class="BLOGCONT2">
			<img src="images/deforestation-concept-illustration_114360-8726.jpg" alt="">
		</div>

	</article>
	<p>Deforestation is the massive act of cutting down trees</p>
	<p>People justify this act which in other words are called as causes of deforestation</p>
	<p> Deforestation poses as a major threat to all beings as shown below</p>
	<article class="blogpost2">
		<div class="BLOGCONT3">
			<img src="images/f.jpg" alt="">
		</div>
			
		<div class="BLOGCONT4">
			<img src="images/m.jpg" alt="">
		</div>
	</article>
		
	<p>AUTHOR: BY NAMBOGO FATUMAH</p>
		<p>DATE PUBLISHED: 12TH JUNE,2023</p>
	<p>&copy; 2023 Rise Bloggers. All rights reserved.</p>
			

</body>
</html>